### ISSUE TITLE
Error when try the GAN

### ISSUE THREAD

**Issue by YakubFahimLuckyarno** [Kitsunetic/head-project#2]
Hi Kitsunetic, 

when I run the run_gan_training.py, I got this error : 

RuntimeError: Given groups=2, weight of size [64, 3, 7], expected input[256, 16, 126] to have 6 channels, but got 16 channels instead

I use the dataset generated from GenerateDataset.ipynb, then rename it as in the code

**Comment by Kitsunetic** [comment]
I pushed a commit of [`GenerateDataset.ipynb`](https://github.com/Kitsunetic/head-project/blob/FinalPresentation/GenerateDataset.ipynb).
I think I unintentionally removed dataset generation code for GAN.

And `run_gan_training.py` do standardization at [line 25](https://github.com/Kitsunetic/head-project/blob/620d6a146a8a954a9c8bee994d1aabf924a4f4a2/run_gan_training.py#L25), but `run_training.py` don't.
You should update the values `MEANS` and `STDS` at line 15~16 with average and standard deviation of your dataset.

Thank you.

**Comment by YakubFahimLuckyarno** [comment]
> I pushed a commit of [`GenerateDataset.ipynb`](https://github.com/Kitsunetic/head-project/blob/FinalPresentation/GenerateDataset.ipynb).
> I think I unintentionally removed dataset generation code for GAN.
> 
> And `run_gan_training.py` do standardization at [line 25](https://github.com/Kitsunetic/head-project/blob/620d6a146a8a954a9c8bee994d1aabf924a4f4a2/run_gan_training.py#L25), but `run_training.py` don't.
> You should update the values `MEANS` and `STDS` at line 15~16 with average and standard deviation of your dataset.
> 
> Thank you.

Thank you very much for your reply. Yes, now the dataset is already worked. Then, in the line 25, I modified the code from this: 

self.X = (self.X - MEANS.reshape(1, 1, 6)) / STDS.reshape(1, 1, 6)
self.Y = (self.Y - MEANS[:3].reshape(1, 1, 3)) / STDS[:3].reshape(1, 1, 3)

into this:

meansX = torch.mean(self.X,0)
meansY = torch.mean(self.Y,0)
stdsX = torch.std(self.X,0)
stdsY = torch.std(self.Y,0)
self.X = (self.X - meansX) / stdsX
self.Y = (self.Y - meansY) / stdsY

**Comment by Kitsunetic** [comment]
OK thank you.

Then... is there no errors?

**Comment by YakubFahimLuckyarno** [comment]
> OK thank you.
> 
> Then... is there no errors?

After I tried with my lab's datasets, it worked fine with no error. 

But, in my case, I need the metrics of 99percentile of each yaw, pitch, roll. So, how can I add it?

**Comment by Kitsunetic** [comment]
At line 305, I'm calculating 99percentile of RMS like this.

```python
diffs = torch.cat(diffs)  # (B, 3)
mae = diffs.abs().mean(dim=0)  # (3, ) --> yaw, pitch, roll
rms = mae.square().sum().div(3).sqrt()  # (1, )
tile = diffs.square().mean(dim=1).sqrt().numpy()  # (B, )
tile99 = np.percentile(tile, 99)
print(f'[{epoch:03d}/{args.epochs:03d}] Validate GAN: '
      f'yaw {mae[0].item():.4f}, '
      f'pitch {mae[1].item():.4f}, '
      f'roll {mae[2].item():.4f}, '
      f'rms {rms.item():.4f}, '
      f'tile99 {tile99:.4f}')
```

Similarly, I think you can get 99percentile of each yaw, pitch, roll like this.

```python
yaw = diffs[:, 0]
pitch = diffs[:, 1]
roll = diffs[:, 2]

yaw_99percentile = np.percentile(yaw.numpy(), 99)
pitch_99percentile = np.percentile(pitch.numpy(), 99)
roll_99percentile = np.percentile(roll.numpy(), 99)
```

But I didn't tested this code will work or the calculation is correct.
<br>

And if this project helpful, please click the Star :)  
Thank you.
